using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using System.Net;
using System.Net.Mail;

namespace Group1_PRN222.Controllers;

public interface IEmailSender
{
    Task SendEmailAsync(string email, string subject, string message);
}

public class EmailSender : IEmailSender
{
    public Task SendEmailAsync(string toMail, string subject, string message)
    {
        var fromMail = "anhdnhhe176689@fpt.edu.vn"; //TODO: add a custom mail here
        var fromPassword = "hcoa fwsp bjhu jwxm";   //App password generated by Google

        var fromAddress = new MailAddress(fromMail, "CloneEbayApp");
        var toAddress = new MailAddress(toMail, "New Registrated User");

        var client = new SmtpClient
        {
            Host = "smtp.gmail.com",
            Port = 587,
            EnableSsl = true,
            DeliveryMethod = SmtpDeliveryMethod.Network,
            UseDefaultCredentials = false,
            Credentials = new NetworkCredential(fromAddress.Address, fromPassword)
        };

        return client.SendMailAsync(
            new MailMessage(fromAddress, toAddress)
            {
                Subject = subject,
                Body = message,
                IsBodyHtml = true
            }
        );
    }
}
